# Generated by Django 2.2 on 2020-04-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20200418_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='company',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.TextField(default=''),
        ),
    ]
