# Generated by Django 2.2 on 2020-04-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20200419_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='category',
        ),
        migrations.RemoveField(
            model_name='level',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='levelupcategory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='resourcecategory',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='LevelUpCategory',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='ResourceCategory',
        ),
    ]
